
modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="ARR"

[[mods]] #mandatory

modId= "jeed" #mandatory

version = "${version}"

displayName="Just Enough Effects Descriptions" #mandatory

logoFile="icon.png" #optional

credits="Mehvahdjukaar" #optional

authors="MehVahdJukaar" #optional

itemIcon="minecraft:painting" #catalogue icon

description='''
REI/JEI addon that shows effects and their descriptions
'''

[modproperties.jeed]
    catalogueItemIcon = "minecraft:potion" #catalogue icon


[[dependencies.jeed]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.jeed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.21)"
    ordering="NONE"
    side="BOTH"
